title: The Long Story Shorter
description: Publishing hopeful tries his best
footer_text: Copyright 2020 Nick Short
header_feature_image: ../uploads/pages.jpg
header_text: My Dream Blog
header_text_color: "#ffffff"
bannerheight: 20vmax
logo: ../uploads/logo.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: false
